# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5 # don’t let the bot flood you
    groups:                     # roll minor+patch releases into one PR
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Track base images in Dockerfile and docker-compose
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      ignore:                    # avoid breaking jumps to Node LTS-next
        - dependency-name: "node"
          update-types: ["version-update:semver-major"]
