# This creates a local development environment with hot reloading
# It's intentionally as similar as possible to the production environment
# Make sure to have a .env file in the same directory as this file

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - my_network
        volumes:
            - .:/app # Mount entire directory for hot reloading
            - /app/node_modules # Don't overwrite node_modules
        environment:
            - NODE_ENV=development # Enables hot reloading
            - AUTH_URL=http://localhost:3000/api/auth # Development auth URL
            - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB} # Connect to DB on host

    db:
        image: postgres:17.5
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - my_network

volumes:
    postgres_data:

networks:
    my_network:
        name: my_network
        driver: bridge
