# This Dockerfile is used for development purposes, i.e. in combination with `docker-compose.dev.yml`

FROM node:24.18.0-alpine3.23

# Keep in sync with "packageManager" in package.json
ARG PNPM_VERSION=10.29.3
RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate

WORKDIR /app

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Auth.js requirements
ENV PORT=3000

# The rest will be mounted at runtime
EXPOSE 3000
CMD ["pnpm", "run", "dev:docker"]
