name: Initial deploy to Elastx

on:
  workflow_dispatch:

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Export GitHub secrets into environment variables"
            export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
            export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
            export POSTGRES_DB="${{ secrets.POSTGRES_DB }}"
            export EMAIL="${{ secrets.EMAIL }}"
            export AUTH_GITHUB_ID="${{ secrets.AUTH_GITHUB_ID }}"
            export AUTH_GITHUB_SECRET="${{ secrets.AUTH_GITHUB_SECRET }}"
            export AUTH_SECRET="${{ secrets.AUTH_SECRET }}"

            echo "Cloning the repository"
            git clone https://github.com/Vasteras-Stadsmission/matkassen.git ~/myapp

            echo "Change directory to the app folder"
            cd ~/myapp

            echo "Run the deploy script"
            chmod +x deploy.sh
            ./deploy.sh
            echo "Deployment completed"
