name: Initial deploy to Elastx

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Target environment'
                required: true
                type: choice
                options:
                  - production
                  - staging
                default: 'staging'

jobs:
    deploy:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set server host based on environment
              id: set-host
              run: |
                if [ "${{ github.event.inputs.environment }}" == "production" ]; then
                  echo "server_host=${{ secrets.SERVER_HOST_PRODUCTION }}" >> $GITHUB_OUTPUT
                else
                  echo "server_host=${{ secrets.SERVER_HOST_STAGING }}" >> $GITHUB_OUTPUT
                fi

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.2.2
              with:
                  host: ${{ steps.set-host.outputs.server_host }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      echo "Export GitHub secrets into environment variables"
                      export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
                      export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
                      export POSTGRES_DB="${{ secrets.POSTGRES_DB }}"
                      export EMAIL="${{ secrets.EMAIL }}"
                      export AUTH_GITHUB_ID="${{ secrets.AUTH_GITHUB_ID }}"
                      export AUTH_GITHUB_SECRET="${{ secrets.AUTH_GITHUB_SECRET }}"
                      export AUTH_SECRET="${{ secrets.AUTH_SECRET }}"

                      echo "Cloning the repository"
                      git clone https://github.com/Vasteras-Stadsmission/matkassen.git ~/myapp

                      echo "Change directory to the app folder"
                      cd ~/myapp

                      echo "Run the deploy script"
                      chmod +x deploy.sh
                      ./deploy.sh
                      echo "Deployment completed"
