name: Lint and Prettier

on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [main]

# Prevent multiple workflow runs
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Install dependencies
              run: bun install
            - name: Run linter
              run: bun run lint
            - name: Check TypeScript types
              run: bun run typecheck
            - name: Check formatting
              run: bun run format-check
